services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ecommercedb
      POSTGRES_USER: ecommerce
      POSTGRES_PASSWORD: ecommerce123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: servico-ecommerce:latest
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/ecommercedb
      SPRING_DATASOURCE_USERNAME: ecommerce
      SPRING_DATASOURCE_PASSWORD: ecommerce123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      APP_ADMIN_USERNAME: ${APP_ADMIN_USERNAME:-admin}
      APP_ADMIN_PASSWORD: ${APP_ADMIN_PASSWORD:-admin}

volumes:
  pgdata:
